// Generated by Haxe 4.1.2
(function ($global) { "use strict";
var App = function() { };
App.main = function() {
	window.onload = function() {
		var text = process.platform + " " + process.arch;
		window.document.getElementById("system-version").textContent = text;
		var text = "node " + process.version;
		window.document.getElementById("node-version").textContent = text;
		var text = "electron " + process.versions["electron"];
		window.document.getElementById("electron-version").textContent = text;
		js_node_ChildProcess.spawn("haxe",["-version"]).stdout.on("data",function(buf) {
			var version = buf.toString();
			window.document.getElementById("haxe-version").textContent = "haxe " + version;
		});
	};
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_node_ChildProcess = require("child_process");
App.main();
})({});

//# sourceMappingURL=app.js.map