// Generated by Haxe 4.1.2
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	electron_main_App.on("ready",function(e) {
		var win = new electron_main_BrowserWindow({ width : 720, height : 480, webPreferences : { nodeIntegration : true}});
		win.on("closed",function() {
			win = null;
		});
		win.loadFile("app.html");
		var tray = new electron_main_Tray("" + __dirname + "/icon-192.png");
	});
	electron_main_App.on("window-all-closed",function(e) {
		if(process.platform != "darwin") {
			electron_main_App.quit();
		}
	});
};
var electron_main_App = require("electron").app;
var electron_main_BrowserWindow = require("electron").BrowserWindow;
var electron_main_Tray = require("electron").Tray;
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});

//# sourceMappingURL=main.js.map